debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/certs/self.crt"
      keyFile = "/etc/certs/self.key"

[docker]
domain = "docker.local"
watch = true

[log]
level = "DEBUG"
  
[api]
entryPoint = "traefik"
dashboard = true

[accessLog]
